{% set version = "2.7" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-animation
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/animation_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/animation/animation_{{ version }}.tar.gz
  sha256: 88418f1b04ec785963bad492f30eb48b05914e9e5d88c7eef705d949cbd7e469

build:
  number: 3
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-magick
  run:
    - r-base
    - r-magick
    - imagemagick
    - ffmpeg

test:
  commands:
    - $R -e "library('animation')"           # [not win]
    - "\"%R%\" -e \"library('animation')\""  # [win]

about:
  home: https://yihui.name/animation
  license: GPL-2.0-or-later
  summary: Provides functions for animations in statistics, covering topics in probability theory, mathematical statistics, multivariate statistics, non-parametric statistics, sampling survey, linear models, time series, computational statistics, data mining and machine learning. These functions may be helpful in teaching
    statistics and data analysis. Also provided in this package are a series of functions to save animations to various formats, e.g. Flash, 'GIF', HTML pages, 'PDF' and videos. 'PDF' animations can be inserted into 'Sweave' / 'knitr' easily.
  license_family: GPL
  license_file: 
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
