{% set version = "2.6" %}

package:
  name: r-animation
  version: {{ version|replace("-", "_") }}

source:
  fn: animation_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/animation_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/animation/animation_{{ version }}.tar.gz
  sha256: 90293638920ac436e7e4de76ebfd92e1643ccdb0259b62128f16dd0b13245b0a

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  skip: true  # [win]

requirements:
  host:
    - r-base
    - r-magick
  run:
    - r-base
    - r-magick
    - texlive-core
    - imagemagick
    - ffmpeg

test:
  commands:
    - $R -e "library('animation')"

about:
  home: https://yihui.name/animation
  license: GPL (>=2)
  summary: Provides functions for animations in statistics, covering topics in probability theory,
    mathematical statistics, multivariate statistics, non-parametric statistics, sampling
    survey, linear models, time series, computational statistics, data mining and machine
    learning. These functions may be helpful in teaching statistics and data analysis.
    Also provided in this package are a series of functions to save animations to various
    formats, e.g. Flash, 'GIF', HTML pages, 'PDF' and videos. 'PDF' animations can be
    inserted into 'Sweave' / 'knitr' easily. SWF files generation not supported with this distribution
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - dpryan79
    - sachalau
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
