# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_r_base3.4.1
    - CONFIG=osx_r_base3.5.1

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "pC6NYX/e6mKnqFJXr8xGdjAIwDs4gsvDGAMXV/vEqVxyEENyWGb8vwHIBj+2OzKPnzmf5pecjQ3EuXrjoE2be+6j49m9n8zf8bKSVrRtarzUl9HmOza6wNrzQ7q/VScYauJN4aAOc+gDFq94HyOe/mxh2VUAYQlV6AE0muA12aMk41bYsV1pf9YVnS1gDpg+FBmZmAlK4UhJJ0QpoPFeC7qnuZlolbYZ1QQ4gjsBPOdxj0qSNEetaMaHTAtMWeZB45rHXL476ZYg8lQ33VMjDJnfoCZhUa/Vz2ZcDxPvi7f4snzAozh5qGYW3Jt3NpzoinTNrttix9OKdktEdaKZtVI3IY6K9RArHR0nISxM68zAoqEfA/zo9+2UmaiA0qPoLxGvlpQ89sWWdgqhLHiQrlCj8kMaEx4ZVF68UYTqjGZJ0LzF1PdRhwxMMpjrvTHxiLvhdvckeXa5S/+HrgRx61yn20aaYoDqouDGypNav+ALOT+tldxB/U5sUXW2w+4OeBRyWsBqLLfwlyu6w29/JC+icU5eFXp3gebzduJpDlyTE02NlIzsryVioiPrdsamGZRj8NtilzxR+QxX72NRfPn32XPDKFqXiVeYHbRap78ux1QVsR3rtFNAaud2DbuAIvCenwDIXuiRyQb0OXbyDeiwi59auNHO3wupU/E3WP0="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
